### ISSUE TITLE
AUD Connector info

### ISSUE THREAD

**Issue by cedricp** [v-ladimir/audprog#2]
Hi,
This project is very interesting to me. I'd like to use it to flash a SAGEM ECU S3000. I've found the AUD_* pins on the SH7055, but I can't figure out  where are the BOOT_TX/RX pins, could you help me please ?

Best regards

**Comment by cedricp** [comment]
Ok, I think I found it at RxD1 & TxD1 pins.

**Comment by v-ladimir** [comment]
Hi - good to hear that someone is intrested in it :)
You are right - BOOT_RX and BOOT_TX are respective RXD and TXD pins from the SCI1 interface on the CPU, you may refer to the SH7055  datasheet to figure out the bootmode flashing details. This board acts just as simple USB-COM bridge in this case.

**Comment by cedricp** [comment]
Thank you for your reply, can you tell me if WDT is important for flashing purpose ? It seems that it's not used in other flash tools (https://autoelectronica.by/renault-ktag/272-250-sagem-s3000-jtag-ren).
EDIT : I've just read the code a bit, it seems that boottx/bootrx are not used for uploading file ? I see that the code use bitbanging for AUD communication. It's less clear for me how to switch the microcontroller in boot mode, though.
Cheers

**Comment by v-ladimir** [comment]
Hi,

WDT is crucial - otherwise the watchdog IC in the ECU (most probably yours also has it) will reset the CPU in couple of seconds and interrupt the process.

Bootmode flashing is done via Renesas FDT tool, while audprog code covers only reading process, which is done via AUD.

But the tool's hardware covers both parts of the process - reading via AUD using the audprog and bootmode flashing via Renesas FDT tool.

**Comment by cedricp** [comment]
OK, it's more clear now :) I downloaded Renesas Flash tool, but I can't see SH7055, should I use an older version ? Can you share it ?
Edit: found the good tool, looking how to enable boot mode now on the chip
